### ISSUE TITLE
Still seeing a 5,000 row limit when selecting date as one of the dimensions

### ISSUE THREAD

**Issue by ericbrownaustin** [MarkEdmondson1234/searchConsoleR#11]
I'm only receiving 5,000 rows even when using date as one of the dimensions. The console also references a 5,000 row limit in the return. I am using v0.1.2.9002. Is there something I am doing wrong in my call?

![image](https://cloud.githubusercontent.com/assets/11723172/14150535/1caf602c-f66f-11e5-9d71-3ef500642ea4.png)

![image](https://cloud.githubusercontent.com/assets/11723172/14150539/20b984e0-f66f-11e5-8fbc-5104b5f7271e.png)

![image](https://cloud.githubusercontent.com/assets/11723172/14150546/257bb598-f66f-11e5-8c0b-37b19b0527cc.png)

**Comment by MarkEdmondson1234** [comment]
I changed it so it would only walk dates, so you need more than one days worth to see any benefit - I see only 1 day date range in your call. Is there much demand for walking through other dimensions?

**Comment by ericbrownaustin** [comment]
Ah.  I think I understand now.  So, if I walked 2 days of data, it's just binding 2 5,000 (or less) row data frames together?

**Comment by MarkEdmondson1234** [comment]
Yes, it just loops the API calls.

**Comment by ericbrownaustin** [comment]
Is the limit a hard limit set by Google or something that can be changed?  I tried to fork and edit the get_data.R file, but I was unsuccessful.
Btw, thanks for building this tool.  It's really helpful for me.

**Comment by MarkEdmondson1234** [comment]
The 5000 per API call is a hard limit yes, but there is access to a lot more data if you break down like we do here, which is why its worth doing :)

If say you wanted more than 5000 for one particular day, then you could also loop over another dimension, for instance country or device, but I think that would only be worth doing if you have an enormous site, as from what I've seen the 5000th row is usually a 1 impression at position 100+ nothing special. As it stands if you get 90 days * 5000 thats 450,000 rows anyhow.

**Comment by MarkEdmondson1234** [comment]
Following on from this, the API has updated now, and you can get more than 5000 per day.
